const bcrypt = require('bcryptjs');
const { getDB } = require('./database');
const db = getDB();

// Clear existing products
db.prepare('DELETE FROM products').run();

// Admin user
const hash = bcrypt.hashSync('00207DylanRamirezLopez', 12);
db.prepare(`INSERT OR REPLACE INTO users (id, name, email, password) VALUES (1, 'Administrador', 'admin', ?)`)
  .run(hash);

// All 39 products from the original products.js, converted to DB schema
const products = [
  {title:'Nautica Voyage',brand:'Nautica',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'Fragancia fresca y acuática perfecta para el día a día. Notas marinas que evocan la brisa del océano.',notas_salida:'Bergamota, Limón, Notas Verdes',notas_corazon:'Acorde Acuático, Jazmín',notas_fondo:'Ámbar, Musk, Cedro',ocasion:'Casual, Deportiva, Día',duracion:'4-6 horas',estacion:'Primavera, Verano',price50ml:25000,price100ml:45000,full_bottle_price:45000,stock:15,is_featured:1,slug:'nautica-voyage',image:'Perfume-Nautica-Voyage-100ml.png'},
  {title:'Nautica Classic',brand:'Nautica',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'El aroma clásico de Nautica, fresco y masculino.',notas_salida:'Bergamota, Lavanda, Limón',notas_corazon:'Jazmín, Geranio, Salvia',notas_fondo:'Ámbar, Musk, Cedro',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera, Verano',price50ml:22000,price100ml:40000,full_bottle_price:40000,stock:10,is_featured:0,slug:'nautica-classic',image:'Nautica-classic.png'},
  {title:'Nautica N-83',brand:'Nautica',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'Fragancia deportiva y energética.',notas_salida:'Pomelo, Menta, Bergamota',notas_corazon:'Lavanda, Geranio',notas_fondo:'Cedro, Sándalo',ocasion:'Deportiva, Casual',duracion:'4-6 horas',estacion:'Verano',price50ml:20000,price100ml:36000,full_bottle_price:36000,stock:8,is_featured:0,slug:'nautica-n-83',image:'nautica-n-83.png'},
  {title:'Nautica Sport',brand:'Nautica',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'Energía pura con notas cítricas y acuáticas.',notas_salida:'Limón, Naranja, Pomelo',notas_corazon:'Jengibre, Pimienta',notas_fondo:'Musk, Cedro',ocasion:'Deportiva, Casual',duracion:'3-5 horas',estacion:'Verano',price50ml:18000,price100ml:32000,full_bottle_price:32000,stock:12,is_featured:0,slug:'nautica-sport',image:'nautica-sport.png'},
  {title:'Nautica Heritage',brand:'Nautica',genero:'Hombre',familia_olfativa:'Oriental Amaderado',descripcion:'Una fragancia sofisticada con carácter.',notas_salida:'Bergamota, Pimienta Rosa',notas_corazon:'Lavanda, Salvia',notas_fondo:'Cedro, Ámbar, Cuero',ocasion:'Formal, Noche',duracion:'6-8 horas',estacion:'Otoño, Invierno',price50ml:28000,price100ml:48000,full_bottle_price:48000,stock:6,is_featured:0,slug:'nautica-heritage',image:'Nautica-heritage.png'},
  
  {title:'Halloween Mujer',brand:'Halloween',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Fragancia floral y frutal con un toque misterioso.',notas_salida:'Pomelo, Mandarina, Maracuyá',notas_corazon:'Jazmín, Lirio, Violeta',notas_fondo:'Musk, Sándalo, Vainilla',ocasion:'Noche, Cita Romántica',duracion:'6-8 horas',estacion:'Primavera, Otoño',price50ml:32000,price100ml:52000,full_bottle_price:52000,stock:7,is_featured:1,slug:'halloween-mujer',image:'halloween-mujer.png'},
  {title:'Halloween Man X',brand:'Halloween',genero:'Hombre',familia_olfativa:'Oriental Amaderado',descripcion:'Audaz y magnético. Para el hombre moderno.',notas_salida:'Pimienta, Pomelo, Jengibre',notas_corazon:'Lavanda, Salvia, Canela',notas_fondo:'Cedro, Ámbar, Cuero',ocasion:'Noche, Formal',duracion:'8-10 horas',estacion:'Otoño, Invierno',price50ml:35000,price100ml:55000,full_bottle_price:55000,stock:5,is_featured:0,slug:'halloween-man-x',image:'halloween-man-x.png'},
  {title:'Halloween Man Rock On',brand:'Halloween',genero:'Hombre',familia_olfativa:'Oriental Amaderado',descripcion:'Una fragancia rockera con personalidad.',notas_salida:'Pimienta Negra, Bergamota',notas_corazon:'Lavanda, Geranio, Canela',notas_fondo:'Cedro, Cuero, Ámbar',ocasion:'Noche, Fiesta',duracion:'8-10 horas',estacion:'Otoño',price50ml:30000,price100ml:50000,full_bottle_price:50000,stock:4,is_featured:0,slug:'halloween-man-rock-on',image:'halloween-man-rock-on.png'},
  {title:'Halloween Kiss Sexy',brand:'Halloween',genero:'Mujer',familia_olfativa:'Oriental Floral',descripcion:'Seductora y atrevida. Un beso inolvidable.',notas_salida:'Pera, Mandarina, Grosella',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Vainilla, Musk, Sándalo',ocasion:'Noche, Cita',duracion:'6-8 horas',estacion:'Primavera, Otoño',price50ml:28000,price100ml:48000,full_bottle_price:48000,stock:6,is_featured:1,slug:'halloween-kiss-sexy',image:'halloween-kiss-sexy.png'},
  {title:'Halloween Love',brand:'Halloween',genero:'Mujer',familia_olfativa:'Floral Frutal Gourmand',descripcion:'Amor en cada gota. Dulce y cautivadora.',notas_salida:'Frambuesa, Mandarina, Limón',notas_corazon:'Jazmín, Rosa, Violeta',notas_fondo:'Vainilla, Caramelo, Musk',ocasion:'Romántica, Día',duracion:'6-8 horas',estacion:'Primavera',price50ml:26000,price100ml:46000,full_bottle_price:46000,stock:9,is_featured:0,slug:'halloween-love',image:'halloween-love.png'},
  {title:'Mía Me Mine',brand:'Halloween',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Una fragancia juvenil y divertida.',notas_salida:'Pomelo, Mandarina, Frutos Rojos',notas_corazon:'Jazmín, Peonía, Lirio',notas_fondo:'Musk, Sándalo, Ámbar',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera, Verano',price50ml:24000,price100ml:42000,full_bottle_price:42000,stock:11,is_featured:0,slug:'mia-me-mine',image:'Mía-Me-Mine-de-la-línea-Halloween-de-Jesús-del-Pozo.png'},

  {title:'360 Red',brand:'Perry Ellis',genero:'Hombre',familia_olfativa:'Aromático Especiado',descripcion:'Fragancia vibrante y seductora.',notas_salida:'Pimienta, Bergamota, Pomelo',notas_corazon:'Canela, Salvia, Geranio',notas_fondo:'Cedro, Sándalo, Ámbar',ocasion:'Noche, Formal',duracion:'6-8 horas',estacion:'Otoño, Invierno',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:20,is_featured:0,slug:'360-red',image:'380-red.png'},
  {title:'360 Blue',brand:'Perry Ellis',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'Frescura acuática con un toque amaderado.',notas_salida:'Bergamota, Limón, Menta',notas_corazon:'Lavanda, Geranio, Salvia',notas_fondo:'Cedro, Sándalo, Musk',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Verano',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:20,is_featured:0,slug:'360-blue',image:'360-blue.png'},
  {title:'360 Green',brand:'Perry Ellis',genero:'Hombre',familia_olfativa:'Aromático Especiado',descripcion:'Aroma fresco y natural.',notas_salida:'Bergamota, Limón, Albahaca',notas_corazon:'Lavanda, Geranio',notas_fondo:'Cedro, Vetiver',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera, Verano',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:15,is_featured:0,slug:'360-green',image:'360-green.png'},
  {title:'360 Pink',brand:'Perry Ellis',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Femenina y radiante.',notas_salida:'Mandarina, Pomelo, Frambuesa',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Musk, Vainilla, Sándalo',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:18,is_featured:0,slug:'360-pink',image:'360-pink.png'},
  {title:'360 Purple',brand:'Perry Ellis',genero:'Mujer',familia_olfativa:'Oriental Floral',descripcion:'Misteriosa y elegante.',notas_salida:'Pera, Mandarina, Grosella',notas_corazon:'Jazmín, Rosa, Violeta',notas_fondo:'Ámbar, Musk, Vainilla',ocasion:'Noche, Formal',duracion:'6-8 horas',estacion:'Otoño',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:14,is_featured:0,slug:'360-purple',image:'360-purple.png'},
  {title:'360 Coral',brand:'Perry Ellis',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Vibrante y juvenil.',notas_salida:'Naranja, Mandarina, Frutos Rojos',notas_corazon:'Jazmín, Peonía',notas_fondo:'Musk, Sándalo',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera, Verano',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:16,is_featured:0,slug:'360-coral',image:'360-coral.png'},
  {title:'360 White',brand:'Perry Ellis',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Limpia y fresca como una brisa.',notas_salida:'Pera, Mandarina, Lichi',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Musk, Sándalo, Ámbar',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera',price50ml:15000,price100ml:25000,full_bottle_price:25000,stock:17,is_featured:0,slug:'360-white',image:'360-white.png'},

  {title:'Guess Gold',brand:'Guess',genero:'Mujer',familia_olfativa:'Oriental Floral',descripcion:'Oro puro en fragancia. Elegante y sofisticada.',notas_salida:'Mandarina, Pera, Pomelo',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Ámbar, Vainilla, Sándalo',ocasion:'Noche, Formal',duracion:'6-8 horas',estacion:'Otoño, Invierno',price50ml:35000,price100ml:55000,full_bottle_price:55000,stock:5,is_featured:1,slug:'guess-gold',image:'guess-gold.png'},
  {title:'Guess Seductive',brand:'Guess',genero:'Mujer',familia_olfativa:'Oriental Floral',descripcion:'Seducción en cada nota.',notas_salida:'Pera, Mandarina, Frambuesa',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Ámbar, Musk, Vainilla',ocasion:'Noche, Cita',duracion:'6-8 horas',estacion:'Otoño',price50ml:32000,price100ml:52000,full_bottle_price:52000,stock:6,is_featured:0,slug:'guess-seductive',image:'guess-seductive.png'},
  {title:'Guess Tradicional Mujer',brand:'Guess',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'El clásico de Guess para mujer.',notas_salida:'Pomelo, Mandarina, Maracuyá',notas_corazon:'Jazmín, Rosa, Violeta',notas_fondo:'Musk, Sándalo, Vainilla',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera',price50ml:30000,price100ml:50000,full_bottle_price:50000,stock:8,is_featured:0,slug:'guess-tradicional-mujer',image:'guess-tradicional-mujer.png'},

  {title:'Ari by Ariana Grande',brand:'Ariana Grande',genero:'Mujer',familia_olfativa:'Floral Frutal Gourmand',descripcion:'Dulce y femenina como la artista.',notas_salida:'Pera, Frambuesa, Pomelo',notas_corazon:'Rosa, Jazmín, Lirio',notas_fondo:'Vainilla, Musk, Sándalo',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera, Verano',price50ml:38000,price100ml:58000,full_bottle_price:58000,stock:7,is_featured:1,slug:'ari-by-ariana-grande',image:'ari-by-ariana-grande.png'},
  {title:'Meow! by Katy Perry',brand:'Katy Perry',genero:'Mujer',familia_olfativa:'Floral Frutal Gourmand',descripcion:'Divertida y atrevida como Katy.',notas_salida:'Melocotón, Mandarina, Fresas',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Vainilla, Caramelo, Musk',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera',price50ml:30000,price100ml:50000,full_bottle_price:50000,stock:9,is_featured:0,slug:'meow-by-katy-perry',image:'Meow!-de-Katy-Perry.png'},
  {title:'Fantasy by Britney Spears',brand:'Britney Spears',genero:'Mujer',familia_olfativa:'Floral Frutal Gourmand',descripcion:'Un sueño hecho fragancia.',notas_salida:'Lichi, Kiwi, Pomelo',notas_corazon:'Jazmín, Rosa, Orquídea',notas_fondo:'Musk, Vainilla, Sándalo',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera',price50ml:25000,price100ml:42000,full_bottle_price:42000,stock:12,is_featured:0,slug:'fantasy-britney-spears',image:'Fantasy-de-Britney-Spears.png'},
  {title:'Midnight Fantasy by Britney Spears',brand:'Britney Spears',genero:'Mujer',familia_olfativa:'Oriental Frutal',descripcion:'La versión nocturna de Fantasy.',notas_salida:'Frambuesa, Cereza, Ciruela',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Ámbar, Vainilla, Musk',ocasion:'Noche, Fiesta',duracion:'6-8 horas',estacion:'Otoño',price50ml:28000,price100ml:45000,full_bottle_price:45000,stock:10,is_featured:0,slug:'midnight-fantasy-britney-spears',image:'Midnight-Fantasy-de-Britney-Spears.png'},

  {title:'Tommy Hombre',brand:'Tommy Hilfiger',genero:'Hombre',familia_olfativa:'Aromático Especiado',descripcion:'El clásico americano fresco y limpio.',notas_salida:'Pomelo, Menta, Bergamota',notas_corazon:'Lavanda, Geranio, Salvia',notas_fondo:'Cedro, Sándalo, Musk',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera, Verano',price50ml:30000,price100ml:50000,full_bottle_price:50000,stock:10,is_featured:0,slug:'tommy-hombre',image:'tommy-hombre.png'},
  {title:'Tommy Girl',brand:'Tommy Hilfiger',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Frescura juvenil americana.',notas_salida:'Manzana, Mandarina, Grosella',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Musk, Sándalo, Cedro',ocasion:'Casual, Día',duracion:'4-6 horas',estacion:'Primavera',price50ml:30000,price100ml:50000,full_bottle_price:50000,stock:10,is_featured:0,slug:'tommy-girl',image:'tommy-girl.png'},

  {title:'Victorinox Altitud',brand:'Victorinox',genero:'Hombre',familia_olfativa:'Aromático Especiado',descripcion:'Precisión suiza en una fragancia.',notas_salida:'Bergamota, Pomelo, Pimienta',notas_corazon:'Lavanda, Geranio, Salvia',notas_fondo:'Cedro, Ámbar, Musk',ocasion:'Formal, Trabajo',duracion:'8-10 horas',estacion:'Todo el año',price50ml:35000,price100ml:55000,full_bottle_price:55000,stock:5,is_featured:0,slug:'victorinox-altitud',image:'Victorinox-ALTITUD.png'},

  {title:'Acqua di Gio Profondo',brand:'Giorgio Armani',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'La profundidad del océano en una fragancia.',notas_salida:'Bergamota, Limón, Pomelo',notas_corazon:'Romero, Salvia, Lavanda',notas_fondo:'Ámbar, Musk, Cedro',ocasion:'Formal, Noche',duracion:'8-12 horas',estacion:'Verano, Primavera',price50ml:45000,price100ml:65000,full_bottle_price:65000,stock:8,is_featured:1,decant_2ml:1500,slug:'acqua-di-gio-profondo',image:'acqua-di-gio-profondo.png'},
  {title:'Rasasi Hawas',brand:'Rasasi',genero:'Hombre',familia_olfativa:'Oriental Frutal',descripcion:'Aroma cautivador con notas frutales y marinas.',notas_salida:'Bergamota, Limón, Manzana',notas_corazon:'Canela, Salvia, Geranio',notas_fondo:'Ámbar, Musk, Cuero',ocasion:'Casual, Noche',duracion:'8-12 horas',estacion:'Todo el año',price50ml:35000,price100ml:55000,full_bottle_price:55000,stock:15,is_featured:1,decant_2ml:1400,decant_3ml:1800,decant_5ml:2500,slug:'rasasi-hawas',image:'hawas-for-Men.png'},
  {title:'Rasasi Hawas Ice',brand:'Rasasi',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'La versión helada de Hawas, más fresca.',notas_salida:'Menta, Limón, Pomelo',notas_corazon:'Lavanda, Geranio',notas_fondo:'Musk, Cedro, Ámbar',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Verano',price50ml:35000,price100ml:55000,full_bottle_price:55000,stock:10,is_featured:0,slug:'rasasi-hawas-ice',image:'Hawas-ice.png'},
  {title:'Rasasi Hawas Black',brand:'Rasasi',genero:'Hombre',familia_olfativa:'Oriental Amaderado',descripcion:'Oscuro e intenso. La noche en una fragancia.',notas_salida:'Pimienta Negra, Bergamota',notas_corazon:'Cuero, Tabaco, Canela',notas_fondo:'Ámbar Oscuro, Cedro, Musk',ocasion:'Noche, Formal',duracion:'10-12 horas',estacion:'Invierno',price50ml:38000,price100ml:58000,full_bottle_price:58000,stock:6,is_featured:0,slug:'rasasi-hawas-black',image:'Hawas-Black.png'},

  {title:'Lattafa Yara Candy',brand:'Lattafa',genero:'Mujer',familia_olfativa:'Floral Frutal Gourmand',descripcion:'Dulce como un caramelo.',notas_salida:'Frutas Rojas, Mandarina',notas_corazon:'Jazmín, Rosa, Heliotropo',notas_fondo:'Vainilla, Musk, Sándalo',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera',price50ml:20000,price100ml:32000,full_bottle_price:32000,stock:20,is_featured:0,slug:'lattafa-yara-candy',image:'lattafa-yara-candy.png'},
  {title:'Lattafa Yara Moi',brand:'Lattafa',genero:'Mujer',familia_olfativa:'Oriental Floral',descripcion:'Elegancia oriental con un toque moderno.',notas_salida:'Pera, Mandarina, Frambuesa',notas_corazon:'Jazmín, Rosa, Orquídea',notas_fondo:'Ámbar, Vainilla, Musk',ocasion:'Noche, Formal',duracion:'8-10 horas',estacion:'Otoño',price50ml:22000,price100ml:35000,full_bottle_price:35000,stock:15,is_featured:0,slug:'lattafa-yara-moi',image:'Yara-Moi.png'},
  {title:'Lattafa Yara Tous',brand:'Lattafa',genero:'Mujer',familia_olfativa:'Floral Frutal',descripcion:'Suave y femenina.',notas_salida:'Pomelo, Mandarina, Frutos Rojos',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Musk, Sándalo, Vainilla',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera',price50ml:20000,price100ml:32000,full_bottle_price:32000,stock:18,is_featured:0,slug:'lattafa-yara-tous',image:'lattafa-yara-tous.png'},

  {title:'Club de Nuit Untold',brand:'Armaf',genero:'Hombre',familia_olfativa:'Oriental Amaderado',descripcion:'La historia no contada del lujo.',notas_salida:'Piña, Bergamota, Limón',notas_corazon:'Abedul, Rosa, Jazmín',notas_fondo:'Ámbar, Musk, Vainilla',ocasion:'Noche, Formal',duracion:'8-12 horas',estacion:'Otoño, Invierno',price50ml:28000,price100ml:45000,full_bottle_price:45000,stock:12,is_featured:1,decant_2ml:1300,slug:'club-de-nuit-untold',image:'armaf-club-de-nuit-untold.png'},
  {title:'Club de Nuit Milestone',brand:'Armaf',genero:'Hombre',familia_olfativa:'Oriental Frutal',descripcion:'Un hito en fragancias.',notas_salida:'Piña, Bergamota, Pomelo',notas_corazon:'Abedul, Rosa, Jazmín',notas_fondo:'Musk, Cedro, Vainilla',ocasion:'Noche, Formal',duracion:'8-10 horas',estacion:'Otoño',price50ml:28000,price100ml:45000,full_bottle_price:45000,stock:10,is_featured:0,slug:'club-de-nuit-milestone',image:'Decant-Club-de-Nuit-Milestone.png'},
  {title:'Club de Nuit Sillage',brand:'Armaf',genero:'Hombre',familia_olfativa:'Acuático Aromático',descripcion:'Estela impecable que perdura.',notas_salida:'Bergamota, Limón, Pomelo',notas_corazon:'Jazmín, Rosa, Lirio',notas_fondo:'Musk, Cedro, Ámbar',ocasion:'Casual, Día',duracion:'6-8 horas',estacion:'Primavera, Verano',price50ml:26000,price100ml:42000,full_bottle_price:42000,stock:14,is_featured:0,slug:'club-de-nuit-sillage',image:'Club-de-Nuit-Sillage.png'},
];

const insert = db.prepare(`INSERT INTO products (title, slug, brand, genero, familia_olfativa, descripcion, notas_salida, notas_corazon, notas_fondo, ocasion, duracion, estacion, price50ml, price100ml, full_bottle_price, decant_2ml, decant_3ml, decant_5ml, decant_10ml, stock, image, is_active, is_featured) VALUES (@title, @slug, @brand, @genero, @familia_olfativa, @descripcion, @notas_salida, @notas_corazon, @notas_fondo, @ocasion, @duracion, @estacion, @price50ml, @price100ml, @full_bottle_price, @decant_2ml, @decant_3ml, @decant_5ml, @decant_10ml, @stock, @image, 1, @is_featured)`);

const insertMany = db.transaction((items) => {
  for (const item of items) {
    insert.run({
      title: item.title, slug: item.slug, brand: item.brand || null,
      genero: item.genero || null, familia_olfativa: item.familia_olfativa || null,
      descripcion: item.descripcion || null,
      notas_salida: item.notas_salida || null, notas_corazon: item.notas_corazon || null, notas_fondo: item.notas_fondo || null,
      ocasion: item.ocasion || null, duracion: item.duracion || null, estacion: item.estacion || null,
      price50ml: item.price50ml || 0, price100ml: item.price100ml || 0, full_bottle_price: item.full_bottle_price || 0,
      decant_2ml: item.decants_2ml ?? item.decant_2ml ?? 1200,
      decant_3ml: item.decants_3ml ?? item.decant_3ml ?? 1600,
      decant_5ml: item.decants_5ml ?? item.decant_5ml ?? 2100,
      decant_10ml: item.decants_10ml ?? item.decant_10ml ?? 4000,
      stock: item.stock || 0, is_featured: item.is_featured || 0,
      image: item.image || null
    });
  }
});

insertMany(products);
console.log('✅ Admin actualizado: admin / 00207DylanRamirezLopez');
console.log('✅ Productos insertados:', products.length);
